<?php

declare(strict_types=1);

namespace App;

/**
 * Single-password admin authentication.
 *
 * - Stores nothing in a DB. Verifies submitted password against the bcrypt
 *   hash in ADMIN_PASSWORD_HASH env.
 * - Session cookie hardened: HttpOnly, SameSite=Lax, Secure when configured.
 * - On successful login regenerates the session ID to prevent fixation.
 * - On failure adds a 500ms delay so brute-force is rate-limited without
 *   needing extra infrastructure for a single-writer blog.
 */
final class Auth
{
    private static bool $started = false;

    public static function start(): void
    {
        if (self::$started || session_status() === PHP_SESSION_ACTIVE) {
            self::$started = true;
            return;
        }

        // strict_mode: reject session IDs not generated by us, forcing the
        // server to issue a fresh one if a client presents an unknown id.
        //   Defends against session fixation attempts where an attacker
        //   tries to seed a victim's browser with a known SID.
        // use_only_cookies: never accept the SID from URL parameters.
        ini_set('session.use_strict_mode', '1');
        ini_set('session.use_only_cookies', '1');

        $name = (string) Config::get('SESSION_NAME', 'lazyblog_sess');
        $secure = strtolower((string) Config::get('SESSION_SECURE', 'false')) === 'true';

        // In HTTPS mode, prepend the `__Host-` cookie prefix. Browsers
        // enforce: cookie MUST be `Secure`, path=`/`, no `Domain` attribute.
        // That bans subdomain takeover or path-narrowed shadowing — a
        // stronger guarantee than the bare `Secure` flag alone.
        if ($secure && !str_starts_with($name, '__Host-')) {
            $name = '__Host-' . $name;
        }

        session_name($name);
        session_set_cookie_params([
            'lifetime' => 0,
            'path' => '/',
            'secure' => $secure,
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
        session_start();
        self::$started = true;
    }

    public static function attempt(string $password): bool
    {
        self::start();

        // Per-IP brute-force throttle — sliding 15-min window. After 10
        // failures from one IP, all subsequent attempts return false fast
        // for 15 minutes regardless of the password. Backed by a small
        // JSON file in the system temp dir (single-server scope; for
        // multi-host setups put it on shared storage or swap for Redis).
        $ip = self::clientIp();
        if (self::tooManyFailures($ip)) {
            usleep(500_000);
            return false;
        }

        $hash = (string) Config::get('ADMIN_PASSWORD_HASH', '');
        if ($hash === '') {
            // Soft fail: no hash configured yet — still burn time so callers
            // can't distinguish "no admin set" from "wrong password".
            usleep(500_000);
            self::recordFailure($ip);
            return false;
        }

        if (!password_verify($password, $hash)) {
            usleep(500_000);
            self::recordFailure($ip);
            return false;
        }

        // Successful login — drop the per-IP failure record so legitimate
        // sessions don't carry a strike count after a typo.
        self::clearFailures($ip);
        session_regenerate_id(true);
        // Rotate the CSRF token too so any pre-login captured token is
        // invalidated. Next Csrf::token() call regenerates lazily.
        unset($_SESSION[Csrf::SESSION_KEY]);
        $_SESSION['admin'] = true;
        $_SESSION['admin_since'] = time();
        return true;
    }

    private const RATE_LIMIT_FILE = '/tmp/lazyblog-login-attempts.json';
    private const POST_UNLOCK_FILE = '/tmp/lazyblog-post-unlock-attempts.json';
    private const RATE_LIMIT_MAX = 10;
    private const RATE_LIMIT_WINDOW_SEC = 900;  // 15 minutes

    private static function clientIp(): string
    {
        // Default: REMOTE_ADDR is the only IP source we trust. Behind
        // Cloudflare, every visitor lands on the same edge IP and would
        // share one rate-limit counter, so opt-in to honouring the
        // `CF-Connecting-IP` header via TRUST_CF_CONNECTING_IP=true in
        // .env. We validate the header value as a real IP before using
        // it so a forged header from a non-CF client can't poison the
        // counter (still trust-on-config — operators MUST only enable
        // this when traffic actually comes through Cloudflare). Falls
        // back to REMOTE_ADDR when missing or invalid.
        $trustCf = strtolower((string) Config::get('TRUST_CF_CONNECTING_IP', 'false'));
        if ($trustCf === 'true' || $trustCf === '1') {
            $cf = (string) ($_SERVER['HTTP_CF_CONNECTING_IP'] ?? '');
            if ($cf !== '' && filter_var($cf, FILTER_VALIDATE_IP) !== false) {
                return $cf;
            }
        }
        return (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
    }

    private static function tooManyFailures(string $ip): bool
    {
        return self::tooManyFailuresIn(self::RATE_LIMIT_FILE, $ip);
    }

    private static function recordFailure(string $ip): void
    {
        self::recordFailureIn(self::RATE_LIMIT_FILE, $ip);
    }

    private static function clearFailures(string $ip): void
    {
        self::clearFailuresIn(self::RATE_LIMIT_FILE, $ip);
    }

    // ---- Generic rate-limit primitives (shared with post-unlock) ----

    /** @return array<string,list<int>> */
    private static function loadAttemptsFile(string $path): array
    {
        if (!is_file($path)) {
            return [];
        }
        $raw = @file_get_contents($path);
        if (!is_string($raw) || $raw === '') {
            return [];
        }
        $decoded = json_decode($raw, true);
        return is_array($decoded) ? $decoded : [];
    }

    /** @param array<string,list<int>> $attempts */
    private static function saveAttemptsFile(string $path, array $attempts): void
    {
        @file_put_contents($path, (string) json_encode($attempts), LOCK_EX);
    }

    private static function tooManyFailuresIn(string $path, string $ip): bool
    {
        $attempts = self::loadAttemptsFile($path);
        $timestamps = $attempts[$ip] ?? [];
        $cutoff = time() - self::RATE_LIMIT_WINDOW_SEC;
        $recent = array_values(array_filter($timestamps, static fn (int $t): bool => $t > $cutoff));
        return count($recent) >= self::RATE_LIMIT_MAX;
    }

    private static function recordFailureIn(string $path, string $ip): void
    {
        $attempts = self::loadAttemptsFile($path);
        $cutoff = time() - self::RATE_LIMIT_WINDOW_SEC;
        $timestamps = $attempts[$ip] ?? [];
        $timestamps = array_values(array_filter($timestamps, static fn (int $t): bool => $t > $cutoff));
        $timestamps[] = time();
        $attempts[$ip] = $timestamps;
        // Prune IPs whose latest attempt is also outside the window so the
        // file doesn't grow unbounded.
        foreach ($attempts as $key => $ts) {
            if (max($ts) <= $cutoff) {
                unset($attempts[$key]);
            }
        }
        self::saveAttemptsFile($path, $attempts);
    }

    private static function clearFailuresIn(string $path, string $ip): void
    {
        $attempts = self::loadAttemptsFile($path);
        if (isset($attempts[$ip])) {
            unset($attempts[$ip]);
            self::saveAttemptsFile($path, $attempts);
        }
    }

    // ---- Per-post unlock: session flag + rate-limit (separate file from
    // admin login so a flood of bad guesses on a public post does NOT
    // lock the operator out of /admin/login). ----

    public static function isPostUnlocked(string $slug): bool
    {
        self::start();
        $map = $_SESSION['unlocked_posts'] ?? null;
        return is_array($map) && !empty($map[$slug]);
    }

    public static function markPostUnlocked(string $slug): void
    {
        self::start();
        if (!isset($_SESSION['unlocked_posts']) || !is_array($_SESSION['unlocked_posts'])) {
            $_SESSION['unlocked_posts'] = [];
        }
        $_SESSION['unlocked_posts'][$slug] = true;
    }

    public static function postUnlockTooMany(string $ip): bool
    {
        return self::tooManyFailuresIn(self::POST_UNLOCK_FILE, $ip);
    }

    public static function postUnlockRecordFailure(string $ip): void
    {
        self::recordFailureIn(self::POST_UNLOCK_FILE, $ip);
    }

    public static function postUnlockClearFailures(string $ip): void
    {
        self::clearFailuresIn(self::POST_UNLOCK_FILE, $ip);
    }

    /**
     * Number of failed unlock attempts left in the current sliding window
     * for this IP before the throttle kicks in. Returns 0 once the IP is
     * throttled; returns RATE_LIMIT_MAX for a fresh IP with no history.
     */
    public static function postUnlockAttemptsRemaining(string $ip): int
    {
        $attempts = self::loadAttemptsFile(self::POST_UNLOCK_FILE);
        $cutoff = time() - self::RATE_LIMIT_WINDOW_SEC;
        $recent = array_filter($attempts[$ip] ?? [], static fn (int $t): bool => $t > $cutoff);
        return max(0, self::RATE_LIMIT_MAX - count($recent));
    }

    public static function check(): bool
    {
        self::start();
        return !empty($_SESSION['admin']);
    }

    public static function logout(): void
    {
        self::start();
        $_SESSION = [];
        if (ini_get('session.use_cookies')) {
            $params = session_get_cookie_params();
            setcookie(
                session_name(),
                '',
                [
                    'expires' => time() - 42_000,
                    'path' => $params['path'],
                    'domain' => $params['domain'],
                    'secure' => $params['secure'],
                    'httponly' => $params['httponly'],
                    'samesite' => $params['samesite'],
                ],
            );
        }
        session_destroy();
    }

    /**
     * Guard an admin handler. If not authed, redirect to login preserving
     * the original destination in `?next=` so the user lands back where they
     * tried to go — but only when the URI looks like a sane internal path
     * (starts with `/`, no `//`, no CRLF/control chars). Anything else is
     * dropped and the user lands at /admin after login. REQUEST_URI is
     * attacker-controlled on the first request line, so pre-validating it
     * here closes the open-redirect window cleanly.
     */
    public static function requireAuth(): void
    {
        if (self::check()) {
            return;
        }
        $uri = (string) ($_SERVER['REQUEST_URI'] ?? '');
        $safe = $uri !== ''
            && $uri[0] === '/'
            && !str_starts_with($uri, '//')
            && !preg_match('/[\r\n\t\0]/', $uri);
        if ($safe) {
            Http::redirect('/admin/login?next=' . rawurlencode($uri));
        }
        Http::redirect('/admin/login');
    }
}
